#!/bin/bash
read -p "Enter the mod numberID to add: " MODID

echo "ServerModSetup(\"${MODID}\")" >> ~/steamapps/DST/mods/dedicated_server_mods_setup.lua
echo "Mod ${MODID} has been added successfully."


#추가될 내용 : 모드 존재여부 확인
#모드 페이지 방문하여 존재 자체 여부 확인
#기존 존재여부 확인 - 이미 목록에 있을 경우 메시지
#기존 존배여부 확인 - 목록에 없을 경우 아래의 행동
#정확한 확인을 위해 모드 이름 출력 (웹 페이지에서 정보 확인 : 모드 타이틀, 파일 사이즈, 출시일)
#모드 숫자ID 다음에 주석처리를 통해 추가정보 기재 (타이틀,출시일,사이즈)
#이후 모드 설정을 위한 스크립트 요구
#
